# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import image_pb2 as image__pb2


class ImagesStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UploadImage = channel.stream_unary(
                '/Images/UploadImage',
                request_serializer=image__pb2.ImageChunk.SerializeToString,
                response_deserializer=image__pb2.Ack.FromString,
                )
        self.PullImage = channel.unary_stream(
                '/Images/PullImage',
                request_serializer=image__pb2.ImageQuery.SerializeToString,
                response_deserializer=image__pb2.ImageChunk.FromString,
                )


class ImagesServicer(object):
    """Missing associated documentation comment in .proto file."""

    def UploadImage(self, request_iterator, context):
        """Client-To-Server RPC. Client sends stream to server and an 
        acknowledgement is received once the image is finished uploading
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PullImage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ImagesServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UploadImage': grpc.stream_unary_rpc_method_handler(
                    servicer.UploadImage,
                    request_deserializer=image__pb2.ImageChunk.FromString,
                    response_serializer=image__pb2.Ack.SerializeToString,
            ),
            'PullImage': grpc.unary_stream_rpc_method_handler(
                    servicer.PullImage,
                    request_deserializer=image__pb2.ImageQuery.FromString,
                    response_serializer=image__pb2.ImageChunk.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Images', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Images(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def UploadImage(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/Images/UploadImage',
            image__pb2.ImageChunk.SerializeToString,
            image__pb2.Ack.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PullImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/Images/PullImage',
            image__pb2.ImageQuery.SerializeToString,
            image__pb2.ImageChunk.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
