# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: image.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bimage.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"J\n\nImageChunk\x12\x13\n\timageData\x18\x01 \x01(\x0cH\x00\x12\x0e\n\x04size\x18\x03 \x01(\x03H\x00\x42\x11\n\x0fMetadataOrBytesJ\x04\x08\x02\x10\x03\"a\n\x08Metadata\x12\x0c\n\x04size\x18\x01 \x01(\x03\x12\n\n\x02id\x18\x02 \x01(\x05\x12\x0e\n\x06\x61uthor\x18\x03 \x01(\t\x12+\n\x07\x63reated\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\";\n\x03\x41\x63k\x12\x11\n\timageSize\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x10\n\x08ImageURL\x18\x03 \x01(\t\"U\n\nImageQuery\x12\x0e\n\x06\x61uthor\x18\x01 \x01(\x05\x12\n\n\x02id\x18\x02 \x01(\x05\x12+\n\x07\x63reated\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp2U\n\x06Images\x12\"\n\x0bUploadImage\x12\x0b.ImageChunk\x1a\x04.Ack(\x01\x12\'\n\tPullImage\x12\x0b.ImageQuery\x1a\x0b.ImageChunk0\x01\x62\x06proto3')



_IMAGECHUNK = DESCRIPTOR.message_types_by_name['ImageChunk']
_METADATA = DESCRIPTOR.message_types_by_name['Metadata']
_ACK = DESCRIPTOR.message_types_by_name['Ack']
_IMAGEQUERY = DESCRIPTOR.message_types_by_name['ImageQuery']
ImageChunk = _reflection.GeneratedProtocolMessageType('ImageChunk', (_message.Message,), {
  'DESCRIPTOR' : _IMAGECHUNK,
  '__module__' : 'image_pb2'
  # @@protoc_insertion_point(class_scope:ImageChunk)
  })
_sym_db.RegisterMessage(ImageChunk)

Metadata = _reflection.GeneratedProtocolMessageType('Metadata', (_message.Message,), {
  'DESCRIPTOR' : _METADATA,
  '__module__' : 'image_pb2'
  # @@protoc_insertion_point(class_scope:Metadata)
  })
_sym_db.RegisterMessage(Metadata)

Ack = _reflection.GeneratedProtocolMessageType('Ack', (_message.Message,), {
  'DESCRIPTOR' : _ACK,
  '__module__' : 'image_pb2'
  # @@protoc_insertion_point(class_scope:Ack)
  })
_sym_db.RegisterMessage(Ack)

ImageQuery = _reflection.GeneratedProtocolMessageType('ImageQuery', (_message.Message,), {
  'DESCRIPTOR' : _IMAGEQUERY,
  '__module__' : 'image_pb2'
  # @@protoc_insertion_point(class_scope:ImageQuery)
  })
_sym_db.RegisterMessage(ImageQuery)

_IMAGES = DESCRIPTOR.services_by_name['Images']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _IMAGECHUNK._serialized_start=48
  _IMAGECHUNK._serialized_end=122
  _METADATA._serialized_start=124
  _METADATA._serialized_end=221
  _ACK._serialized_start=223
  _ACK._serialized_end=282
  _IMAGEQUERY._serialized_start=284
  _IMAGEQUERY._serialized_end=369
  _IMAGES._serialized_start=371
  _IMAGES._serialized_end=456
# @@protoc_insertion_point(module_scope)
