# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: posts.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
import content_pb2 as content__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bposts.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\rcontent.proto\"\xab\x01\n\x04Post\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0e\n\x06\x61uthor\x18\x02 \x01(\t\x12\x19\n\x07\x63ontent\x18\x03 \x01(\x0b\x32\x08.Content\x12\x30\n\x0clast_updated\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12+\n\x07\x63reated\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\r\n\x05title\x18\x06 \x01(\t\"\x95\x01\n\tPostQuery\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0e\n\x06\x61uthor\x18\x02 \x01(\t\x12\x30\n\x0clast_updated\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12+\n\x07\x63reated\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\r\n\x05\x63ount\x18\x05 \x01(\x05\"K\n\rPostUploadAck\x12\n\n\x02id\x18\x01 \x01(\x05\x12.\n\nsaved_time\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"e\n\x04\x46\x65\x65\x64\x12\x0f\n\x07\x61uthors\x18\x04 \x03(\t\x12\x14\n\x05posts\x18\x02 \x03(\x0b\x32\x05.Post\x12\x30\n\x0clast_updated\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.TimestampJ\x04\x08\x01\x10\x02\x32}\n\tPostsSync\x12#\n\x0crefreshPosts\x12\n.PostQuery\x1a\x05.Post0\x01\x12!\n\nqueryPosts\x12\n.PostQuery\x1a\x05.Post0\x01\x12(\n\x0buploadPosts\x12\x05.Post\x1a\x0e.PostUploadAck(\x01\x30\x01\x62\x06proto3')



_POST = DESCRIPTOR.message_types_by_name['Post']
_POSTQUERY = DESCRIPTOR.message_types_by_name['PostQuery']
_POSTUPLOADACK = DESCRIPTOR.message_types_by_name['PostUploadAck']
_FEED = DESCRIPTOR.message_types_by_name['Feed']
Post = _reflection.GeneratedProtocolMessageType('Post', (_message.Message,), {
  'DESCRIPTOR' : _POST,
  '__module__' : 'posts_pb2'
  # @@protoc_insertion_point(class_scope:Post)
  })
_sym_db.RegisterMessage(Post)

PostQuery = _reflection.GeneratedProtocolMessageType('PostQuery', (_message.Message,), {
  'DESCRIPTOR' : _POSTQUERY,
  '__module__' : 'posts_pb2'
  # @@protoc_insertion_point(class_scope:PostQuery)
  })
_sym_db.RegisterMessage(PostQuery)

PostUploadAck = _reflection.GeneratedProtocolMessageType('PostUploadAck', (_message.Message,), {
  'DESCRIPTOR' : _POSTUPLOADACK,
  '__module__' : 'posts_pb2'
  # @@protoc_insertion_point(class_scope:PostUploadAck)
  })
_sym_db.RegisterMessage(PostUploadAck)

Feed = _reflection.GeneratedProtocolMessageType('Feed', (_message.Message,), {
  'DESCRIPTOR' : _FEED,
  '__module__' : 'posts_pb2'
  # @@protoc_insertion_point(class_scope:Feed)
  })
_sym_db.RegisterMessage(Feed)

_POSTSSYNC = DESCRIPTOR.services_by_name['PostsSync']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _POST._serialized_start=64
  _POST._serialized_end=235
  _POSTQUERY._serialized_start=238
  _POSTQUERY._serialized_end=387
  _POSTUPLOADACK._serialized_start=389
  _POSTUPLOADACK._serialized_end=464
  _FEED._serialized_start=466
  _FEED._serialized_end=567
  _POSTSSYNC._serialized_start=569
  _POSTSSYNC._serialized_end=694
# @@protoc_insertion_point(module_scope)
